# Generated by Django 6.0.7 on 2026-08-04 11:34

import beats.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('area', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='weekly', max_length=12)),
                ('weekdays', models.JSONField(default=list, validators=[beats.models.validate_weekdays])),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to='accounts.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeatOutlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_ref', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='beats.beat')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BeatPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', max_length=12)),
                ('planned_outlet_count', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid7, editable=False)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='beats.beat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beat_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'beat__name'],
            },
        ),
        migrations.CreateModel(
            name='BeatPlanVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_ref', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=150)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('visited', 'Visited'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_visits', to='beats.beatoutlet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='beats.beatplan')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='beat',
            index=models.Index(fields=['assigned_user', 'is_active'], name='beats_beat_assigne_1dda64_idx'),
        ),
        migrations.AddConstraint(
            model_name='beatoutlet',
            constraint=models.UniqueConstraint(fields=('beat', 'customer_ref'), name='one_stop_per_customer_per_beat'),
        ),
        migrations.AddIndex(
            model_name='beatplan',
            index=models.Index(fields=['user', 'date'], name='beats_beatp_user_id_d18ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='beatplan',
            index=models.Index(fields=['date', 'status'], name='beats_beatp_date_ef7b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='beatplan',
            constraint=models.UniqueConstraint(fields=('user', 'beat', 'date'), name='one_plan_per_beat_per_day'),
        ),
        migrations.AddConstraint(
            model_name='beatplan',
            constraint=models.UniqueConstraint(fields=('user', 'sync_id'), name='one_plan_per_sync_id'),
        ),
        migrations.AddIndex(
            model_name='beatplanvisit',
            index=models.Index(fields=['plan', 'status'], name='beats_beatp_plan_id_0b6152_idx'),
        ),
        migrations.AddConstraint(
            model_name='beatplanvisit',
            constraint=models.UniqueConstraint(fields=('plan', 'customer_ref'), name='one_visit_per_customer_per_plan'),
        ),
    ]
