# Generated by Django 6.0.7 on 2026-08-06 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Whole number'), ('decimal', 'Decimal'), ('boolean', 'Yes/No')], max_length=10)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_code', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Failed sign-in'), ('logout', 'Signed out'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('settings_update', 'Settings changed'), ('permissions_update', 'Permissions changed')], max_length=20)),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('request_path', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='administrat_created_02e1c0_idx'), models.Index(fields=['actor', '-created_at'], name='administrat_actor_i_7aa687_idx'), models.Index(fields=['entity', 'entity_id'], name='administrat_entity_407a8b_idx'), models.Index(fields=['action', '-created_at'], name='administrat_action_0f7900_idx')],
            },
        ),
    ]
