# Generated by Django 6.0.7 on 2026-08-06 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_applied', models.PositiveIntegerField(default=0)),
                ('records_duplicate', models.PositiveIntegerField(default=0)),
                ('records_conflicted', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sync batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncDownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('records_returned', models.PositiveIntegerField(default=0)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('local_id', models.CharField(max_length=128)),
                ('server_id', models.CharField(blank=True, default='', max_length=64)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('duplicate', 'Duplicate'), ('conflict', 'Conflict'), ('failed', 'Failed')], max_length=12)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sync.syncbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncbatch',
            index=models.Index(fields=['user', 'started_at'], name='sync_syncba_user_id_87ea80_idx'),
        ),
        migrations.AddIndex(
            model_name='syncbatch',
            index=models.Index(fields=['device_id'], name='sync_syncba_device__cebb4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncbatch',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='one_batch_per_key_per_user'),
        ),
        migrations.AddIndex(
            model_name='syncdownloadlog',
            index=models.Index(fields=['user', 'created_at'], name='sync_syncdo_user_id_8b2610_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['batch', 'status'], name='sync_syncre_batch_i_450e96_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['entity_type', 'status'], name='sync_syncre_entity__e1bf45_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['entity_type', 'local_id', 'status'], name='sync_syncre_entity__f3b922_idx'),
        ),
    ]
