# Generated by Django 6.0.7 on 2026-08-04 09:19

import accounts.managers
import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('mark_attendance', 'Mark attendance'), ('log_site_visits', 'Log site visits'), ('plan_beats', 'Plan beats'), ('onboard_customers', 'Onboard customers and sites'), ('place_orders', 'Place orders'), ('approve_discount', 'Approve discounts above the field cap'), ('cancel_orders', 'Cancel orders'), ('view_pricing', 'View the full rate card'), ('view_reports', 'View reports'), ('view_team_reports', "View the whole team's figures"), ('export_data', 'Export report data'), ('manage_users', 'Add and suspend users'), ('manage_roles', 'Edit roles and permissions'), ('edit_master_data', 'Edit master data'), ('edit_configuration', 'Change app configuration')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('group', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9\\-/]{1,19}$', 'Use letters, digits, hyphen or slash, e.g. SFM-0142.')])),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use E.164 format, e.g. +919876543210.')])),
                ('manager_path', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_photo_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended')], default='invited', max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='Unset automatically unless the status is Active.')),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.designation')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('zone', 'Zone'), ('region', 'Region'), ('city', 'City'), ('beat_area', 'Beat area')], default='city', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=512)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.territory')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTerritory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_from', models.DateField(default=django.utils.timezone.localdate)),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='accounts.territory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user territories',
                'ordering': ['-is_primary', 'territory__name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='territories',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserTerritory', to='accounts.territory'),
        ),
        migrations.AddIndex(
            model_name='territory',
            index=models.Index(fields=['kind', 'is_active'], name='accounts_te_kind_25524a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userterritory',
            constraint=models.UniqueConstraint(fields=('user', 'territory'), name='one_link_per_user_and_territory'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'is_active'], name='accounts_us_departm_98cc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='accounts_us_status_6bbe13_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('mobile__isnull', False), _connector='OR'), name='user_has_a_login_identifier'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('reporting_manager', models.F('id')), _negated=True), name='user_is_not_their_own_manager'),
        ),
    ]
