# Generated by Django 6.0.7 on 2026-08-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inviterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('mark_attendance', 'Mark attendance'), ('log_site_visits', 'Log site visits'), ('plan_beats', 'Plan beats'), ('onboard_customers', 'Onboard customers and sites'), ('place_orders', 'Place orders'), ('approve_discount', 'Approve discounts above the field cap'), ('cancel_orders', 'Cancel orders'), ('view_pricing', 'View the full rate card'), ('view_reports', 'View reports'), ('view_team_reports', "View the whole team's figures"), ('export_data', 'Export report data'), ('manage_users', 'Add and suspend users'), ('manage_roles', 'Edit roles and permissions'), ('edit_master_data', 'Edit master data'), ('edit_configuration', 'Change app configuration'), ('approve_registrations', 'Approve or reject invite requests'), ('view_audit_logs', 'Read the audit trail')]},
        ),
    ]
