# Generated by Django 6.0.7 on 2026-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_businesspermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviterequest',
            name='password_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
    ]
