# Generated by Django 6.0.7 on 2026-08-06 09:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10)),
                ('version', models.CharField(max_length=20)),
                ('minimum_supported_version', models.CharField(max_length=20)),
                ('force_update', models.BooleanField(default=False)),
                ('download_url', models.URLField(blank=True, default='')),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform', '-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_current'], name='appinfo_app_platfor_85fe01_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'version'), name='one_release_per_version')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='appinfo_ann_is_acti_b8123d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('privacy', 'Privacy policy'), ('terms', 'Terms and conditions')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'is_published', '-effective_date'], name='appinfo_leg_kind_1a5a01_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='one_version_per_document_kind')],
            },
        ),
    ]
