# Generated by Django 6.0.7 on 2026-08-06 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_inviterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('contact_person', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('type', models.CharField(choices=[('dealer', 'Dealer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('contractor', 'Contractor'), ('architect', 'Architect')], default='retailer', max_length=12)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid7, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_customers', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.territory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='customers_c_type_49cb13_idx'), models.Index(fields=['city'], name='customers_c_city_571324_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='one_customer_per_name_per_city')],
            },
        ),
    ]
