# Generated by Django 6.0.7 on 2026-08-05 09:46

import django.db.models.deletion
import django.utils.timezone
import sitevisits.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_inviterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('customer_ref', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=16)),
                ('stage', models.CharField(choices=[('foundation', 'Foundation'), ('structure', 'Structure'), ('brickwork', 'Brickwork'), ('plaster', 'Plastering'), ('finishing', 'Finishing'), ('completed', 'Completed')], default='foundation', max_length=12)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_closure', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='accounts.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('new_lead', 'New lead'), ('follow_up', 'Follow-up'), ('order_collection', 'Order collection'), ('payment_collection', 'Payment collection'), ('technical_support', 'Technical support'), ('complaint', 'Complaint')], default='follow_up', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=12)),
                ('check_in_at', models.DateTimeField()),
                ('check_in_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('check_in_address', models.CharField(blank=True, default='', max_length=255)),
                ('check_in_distance_meters', models.FloatField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('check_out_address', models.CharField(blank=True, default='', max_length=255)),
                ('stage_observed', models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('structure', 'Structure'), ('brickwork', 'Brickwork'), ('plaster', 'Plastering'), ('finishing', 'Finishing'), ('completed', 'Completed')], default='', max_length=12)),
                ('competitor_brands', models.JSONField(blank=True, default=list)),
                ('expected_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid7, editable=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='sitevisits.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=sitevisits.models.visit_photo_path)),
                ('tag', models.CharField(choices=[('site_front', 'Site front'), ('work_in_progress', 'Work in progress'), ('material_stack', 'Material stack'), ('competitor_product', 'Competitor product'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sitevisits.sitevisit')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['stage', 'is_active'], name='sitevisits__stage_64917d_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['customer_ref'], name='sitevisits__custome_7a1655_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['user', '-check_in_at'], name='sitevisits__user_id_b3ae27_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['status'], name='sitevisits__status_5115f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['follow_up_date'], name='sitevisits__follow__87c906_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitevisit',
            constraint=models.UniqueConstraint(fields=('user', 'sync_id'), name='one_visit_per_sync_id'),
        ),
        migrations.AddConstraint(
            model_name='sitevisit',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_out_at__gte', models.F('check_in_at')), _connector='OR'), name='visit_check_out_after_check_in'),
        ),
        migrations.AddIndex(
            model_name='sitevisitimage',
            index=models.Index(fields=['visit', 'tag'], name='sitevisits__visit_i_2b4e31_idx'),
        ),
    ]
