# Generated by Django 6.0.7 on 2026-08-04 11:05

import attendance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='accounts.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('punch_in_at', models.DateTimeField()),
                ('punch_in_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('punch_in_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('punch_in_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('punch_in_address', models.CharField(blank=True, default='', max_length=255)),
                ('punch_in_selfie', models.ImageField(blank=True, null=True, upload_to=attendance.models.selfie_path)),
                ('punch_in_distance_meters', models.FloatField(blank=True, null=True)),
                ('punch_in_within_fence', models.BooleanField(blank=True, null=True)),
                ('punch_out_at', models.DateTimeField(blank=True, null=True)),
                ('punch_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('punch_out_address', models.CharField(blank=True, default='', max_length=255)),
                ('punch_out_selfie', models.ImageField(blank=True, null=True, upload_to=attendance.models.selfie_path)),
                ('punch_out_distance_meters', models.FloatField(blank=True, null=True)),
                ('punch_out_within_fence', models.BooleanField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('worked_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('mobile', 'Mobile app'), ('web', 'Web'), ('admin', 'Entered by an administrator')], default='mobile', max_length=10)),
                ('sync_id', models.UUIDField(default=uuid.uuid7, editable=False)),
                ('punch_out_sync_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                ('punch_in_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_ins', to='attendance.geofence')),
                ('punch_out_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_outs', to='attendance.geofence')),
            ],
            options={
                'verbose_name_plural': 'attendance',
                'ordering': ['-punch_in_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_6910a5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', '-day'], name='attendance__user_id_ad0b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['day', 'is_late'], name='attendance__day_f19e0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='one_attendance_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'sync_id'), name='one_record_per_sync_id'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('punch_out_at__isnull', True), ('punch_out_at__gte', models.F('punch_in_at')), _connector='OR'), name='punch_out_after_punch_in'),
        ),
    ]
