# Generated by Django 6.0.7 on 2026-08-06 06:44

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, max_length=24, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('steel', 'TMT steel'), ('paint', 'Paint & putty'), ('adhesive', 'Adhesives'), ('tiles', 'Tiles & stone'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('other', 'Other')], default='other', max_length=12)),
                ('brand', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(choices=[('bag', 'per bag'), ('kg', 'per kg'), ('tonne', 'per tonne'), ('litre', 'per litre'), ('piece', 'per piece'), ('box', 'per box'), ('sqft', 'per sq ft')], default='piece', max_length=8)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('sync_id', models.UUIDField(default=uuid.uuid7, editable=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'active'], name='products_pr_categor_748e0c_idx'), models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__lte', models.F('mrp'))), name='selling_price_within_mrp'), models.CheckConstraint(condition=models.Q(('mrp__gte', 0), ('selling_price__gte', 0), ('gst_percent__gte', 0)), name='prices_are_not_negative')],
            },
        ),
    ]
